kitchen_app/urls.py
from django.urls import path

from kitchen_app.views import (index,
                               TypesOfDishesListView,
                               TypesOfDishesCreateView,
                               TypesOfDishesUpdateView,
                               TypesOfDishesDeleteView,
                               DishesListView,
                               DishesCreateView,
                               DishesUpdateView,
                               DishesDeleteView,
                               IngredientsListView,
                               IngredientsCreateView,
                               IngredientsUpdateView,
                               IngredientsDeleteView,
                               CooksListView,
                               CooksDetailView,
                               CooksCreateView,
                               CooksUpdateView,
                               CooksDeleteView,
                               DishesDetailView)

urlpatterns = [
    path("", index, name="index"),
    path("types-of-dishes/",
         TypesOfDishesListView.as_view(),
         name="dishtype-list"),
    path("types-of-dishes/create/",
         TypesOfDishesCreateView.as_view(),
         name="dishtype-create"),

    path("types-of-dishes/<int:pk>/update/",
         TypesOfDishesUpdateView.as_view(),
         name="dishtype-update"),

    path("types-of-dishes/<int:pk>/delete/",
         TypesOfDishesDeleteView.as_view(),
         name="dishtype-delete"),

    path("dishes/",
         DishesListView.as_view(),
         name="dish-list"),

    path("dishes/<int:pk>/",
         DishesDetailView.as_view(),
         name="dish-detail"),

    path("dishes/create/",
         DishesCreateView.as_view(),
         name="dish-create"),

    path("dishes/<int:pk>/update/",
         DishesUpdateView.as_view(),
         name="dish-update"),

    path("dishes/<int:pk>/delete/",
         DishesDeleteView.as_view(),
         name="dish-delete"),

    path("ingredients/",
         IngredientsListView.as_view(),
         name="ingredient-list"),

    path("ingredients/create/",
         IngredientsCreateView.as_view(),
         name="ingredient-create"),

    path("ingredients/<int:pk>/update/",
         IngredientsUpdateView.as_view(),
         name="ingredient-update"),

    path("ingredients/<int:pk>/delete/",
         IngredientsDeleteView.as_view(),
         name="ingredient-delete"),

    path("cooks/",
         CooksListView.as_view(),
         name="cook-list"),

    path("cooks/<int:pk>",
         CooksDetailView.as_view(),
         name="cook-detail"),

    path("cooks/create/",
         CooksCreateView.as_view(),
         name="cook-create"),

    path("cooks/<int:pk>/update/",
         CooksUpdateView.as_view(),
         name="cook-update"),

    path("cooks/<int:pk>/delete/",
         CooksDeleteView.as_view(),
         name="cook-delete"),
]

app_name = "kitchen_app"

kitchen_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("kitchen_app.urls", namespace="kitchen_app")),
]

kitchen_app/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from kitchen_management import settings


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        default=0
    )

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class DishType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=10)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name="dish_ingredients"
    )
    cooks = models.ManyToManyField(
        Cook,
        related_name="dishes"
    )

    def clean(self):
        super().clean()

        if self.price is not None and self.price <= 0:
            raise ValidationError("Price must be grater than 0")

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} {self.price}"

kitchen_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from .models import DishType, Dish, Ingredient, Cook


class DishTypeForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = "__all__"

        widgets = {
            "name": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border "
                    "border-dark border-2 shadow-lg"}),
        }


class DishForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = "__all__"

        widgets = {
            "name": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "description": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "price": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "dish_type": forms.Select(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "ingredients": forms.CheckboxSelectMultiple(attrs={
                "class":
                    "form-control border border-dark"
                    " border-2 shadow-lg"},),
            "cooks": forms.SelectMultiple(attrs={
                "class":
                    "form-control border border-dark"
                    " border-2 shadow-lg"}, ),
        }

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price is not None and price <= 0:
            raise ValidationError("Price must be greater than 0")
        return price


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = "__all__"

        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control form-control-lg border"
                         " border-dark border-2 shadow-lg"}),
        }


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

        widgets = {
            "username": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "years_of_experience": forms.NumberInput(attrs={
                "type": "number",
                "min": 0,
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "first_name": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "last_name": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "password": forms.PasswordInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "password2": forms.PasswordInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
        }


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience", "first_name", "last_name"]

        widgets = {
            "years_of_experience": forms.NumberInput(attrs={
                "type": "number",
                "min": 0,
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "first_name": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
            "last_name": forms.TextInput(attrs={
                "class":
                    "form-control form-control-lg border"
                    " border-dark border-2 shadow-lg"}),
        }


class CookNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by name",
            "class":
                "form-control form-control-lg border"
                " border-light border-2 shadow-lg",
            "style": "color:white;"
        })
    )


class IngredientNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by ingredient name",
            "class":
                "form-control form-control-lg border"
                " border-light border-2 shadow-lg",
            "style": "color:white;"
        })
    )


class DishNameSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search by dish name",
            "class":
                "form-control form-control-lg border"
                " border-light border-2 shadow-lg",
            "style": "color:white;"
        })
    )

kitchen_app/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from .forms import (DishTypeForm,
                    DishForm,
                    IngredientForm,
                    CookCreationForm,
                    CookUpdateForm,
                    CookNameSearchForm,
                    IngredientNameSearchForm,
                    DishNameSearchForm)
from .models import Cook, DishType, Dish, Ingredient


def index(request):
    num_cooks = get_user_model().objects.all().count()
    num_dish_types = DishType.objects.all().count()
    num_dishes = Dish.objects.all().count()

    context = {
        'num_cooks': num_cooks,
        'num_dish_types': num_dish_types,
        'num_dishes': num_dishes,
    }

    return render(request, "kitchen_app/index.html", context=context)


class TypesOfDishesListView(generic.ListView):
    model = DishType
    template_name = "kitchen_app/dishtype_list.html"
    paginate_by = 8


class TypesOfDishesCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeForm
    success_url = reverse_lazy("kitchen_app:dishtype-list")


class TypesOfDishesUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    form_class = DishTypeForm
    success_url = reverse_lazy("kitchen_app:dishtype-list")


class TypesOfDishesDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen_app:dishtype-list")


class DishesListView(generic.ListView):
    model = Dish
    template_name = "kitchen_app/dish_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishesListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = DishNameSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = DishNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishesDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish

    def get_queryset(self):
        return super().get_queryset().prefetch_related("ingredients")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dish_object = self.get_object()

        dish_ingredients = dish_object.ingredients.all()
        context["ingredients"] = dish_ingredients

        return context


class DishesCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen_app:dish-list")


class DishesUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen_app:dish-list")

    def get_success_url(self):
        dish_pk = self.object.pk

        return reverse("kitchen_app:dish-detail", kwargs={"pk": dish_pk})


class DishesDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen_app:dish-list")


class IngredientsListView(generic.ListView):
    model = Ingredient
    template_name = "kitchen_app/ingredient_list.html"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IngredientsListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = IngredientNameSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = IngredientNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class IngredientsCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    form_class = IngredientForm
    success_url = reverse_lazy("kitchen_app:ingredient-list")


class IngredientsUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    form_class = IngredientForm
    success_url = reverse_lazy("kitchen_app:ingredient-list")


class IngredientsDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    success_url = reverse_lazy("kitchen_app:ingredient-list")


class CooksListView(generic.ListView):
    model = Cook
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CooksListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["search_form"] = CookNameSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = CookNameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                Q(first_name__icontains=form.cleaned_data["name"]) |
                Q(last_name__icontains=form.cleaned_data["name"]) |
                Q(username__icontains=form.cleaned_data["name"])
            )
        return queryset


class CooksDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cook_object = self.get_object()

        cook_dishes = cook_object.dishes.all()
        context["cook_dishes"] = cook_dishes

        return context


class CooksCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen_app:cook-list")


class CooksUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm

    def get_success_url(self):
        cook_pk = self.object.pk

        return reverse("kitchen_app:cook-detail", kwargs={"pk": cook_pk})


class CooksDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen_app:cook-list")

templates/kitchen_app/cook_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="text-white pt-3 mt-n5">Are you sure to delete
    <br>{{ cook.first_name }} {{ cook.last_name }}
    <br> from kitchen?
  </h1>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <form action="" method="post">
            {% csrf_token %}

            <input type="submit" value="Delete" class="btn btn-primary btn-success">
            <a href="{% url "kitchen_app:cook-detail" pk=cook.id %}" class="btn btn-primary btn-danger">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/cook_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <p class="fs-5 fw-bold text-dark">Name: {{ cook.first_name }} {{ cook.last_name }}</p>

          {% if cook.username %}
            <p class="fs-5 fw-bold text-dark">Username: {{ cook.username }}</p>
          {% endif %}

          <p class="fs-5 fw-bold text-dark">Years of experience: {{ cook.years_of_experience }}</p>
          <p class="fs-5 fw-bold text-dark">Dishes:</p>

          <ul class="list-unstyled">
            {% for dish in cook_dishes %}
              <li class="fs-6 text-dark">{{ dish.name }}</li>
            {% endfor %}
          </ul>

          <a href="{% url "kitchen_app:cook-list" %}" class="btn btn-info mt-4">Go back</a>
          <a href="{% url "kitchen_app:cook-update" pk=cook.id %}" class="btn btn-primary btn-success">Update cook</a>
          <a href="{% url "kitchen_app:cook-delete" pk=cook.id %}" class="btn btn-primary btn-danger">Delete cook</a>

        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
  <h1 class="text-white pt-3 mt-7">{{ object|yesno:"Update,Create" }} cook</h1>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit" class="btn btn-primary mt-5">
            {% if object %}
                <a href="{% url "kitchen_app:cook-detail" pk=object.id %}" class="btn btn-secondary mt-5">
                    Back
                </a>
            {% else %}
                <a href="{% url "kitchen_app:cook-list" %}" class="btn btn-secondary mt-5">
                    Back
                </a>
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1 class="text-white pt-3 mt-5">Cooks</h1>

  <form action="" method="get">
      {{ search_form|crispy }}
      <input type="submit" value="Search" class="btn btn-primary mt-2">
    </form>

  {% if cook_list %}
    <table class="table text-white border my-5 align-middle">
      <tr class="fs-4">
        <th>ID</th>
        <th>Name</th>
        <th>Years of experience</th>
      </tr>

    {% for cook in cook_list %}
      <tr class="fs-6">
        <td>
          {{ cook.id }}
        </td>
        <td>
          <a href="{% url "kitchen_app:cook-detail" pk=cook.id %}" class="btn-outline-light text-white">
            {{ cook.first_name }} {{ cook.last_name }}
          </a>
        </td>
        <td>
          {{ cook.years_of_experience }}
        </td>
      </tr>
    {% endfor %}

    </table>
  {% else %}
    <h2 class="text-white pt-3 my-5">There is no any cooks</h2>
  {% endif %}

  <a href="{% url "kitchen_app:cook-create" %}" class="btn btn-primary link-to-page">
      Create new cook
    </a>

{% endblock content %}

templates/kitchen_app/dish_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="text-white pt-3 mt-n5">Are you sure to delete <br>{{ dish.name }}?</h1>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <form action="" method="post">
            {% csrf_token %}

            <input type="submit" value="Delete" class="btn btn-primary btn-success">
            <a href="{% url "kitchen_app:dish-detail" pk=dish.id %}" class="btn btn-primary btn-danger">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/dish_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <p class="fs-5 fw-bold text-dark">Name: {{ dish.name }}</p>
          <p class="fs-5 fw-bold text-dark">Description: {{ dish.description }}</p>
          <p class="fs-5 fw-bold text-dark">Price: {{ dish.price }}</p>
          <p class="fs-5 fw-bold text-dark">Dish type: {{ dish.dish_type.name }}</p>

          <p class="fs-5 fw-bold text-dark">Ingredients:</p>
            <ul class="list-unstyled">
              {% for ingredient in ingredients %}
                <li class="fs-6 text-dark">{{ ingredient.name }}</li>
              {% endfor %}
            </ul>

          <a href="{% url "kitchen_app:dish-list" %}" class="btn btn-info mt-4">Go back</a>
          <a href="{% url "kitchen_app:dish-update" pk=dish.id %}" class="btn btn-primary btn-success">Update dish</a>
          <a href="{% url "kitchen_app:dish-delete" pk=dish.id %}" class="btn btn-primary btn-danger">Delete dish</a>

        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
  <h1 class="text-white pt-3 mt-7">{{ object|yesno:"Update,Create" }} dish</h1>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit" class="btn btn-primary mt-5">
            {% if object %}
                <a href="{% url "kitchen_app:dish-detail" pk=object.id %}" class="btn btn-secondary mt-5">
                    Back
                </a>
            {% else %}
                <a href="{% url "kitchen_app:dish-list" %}" class="btn btn-secondary mt-5">
                    Back
                </a>
            {% endif %}
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1 class="text-white pt-3 mt-5">Dishes</h1>

  <form action="" method="get">
    {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-primary mt-2">
  </form>

  <div class="table-responsive">
  {% if dish_list %}
    <table class="table text-white border my-4 align-middle">
      <tr class="fs-4">
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Dish type</th>
      </tr>

    {% for dish in dish_list %}
      <tr class="fs-6">
        <td>
          {{ dish.id }}
        </td>
        <td>
          <a href="{% url "kitchen_app:dish-detail" pk=dish.id %}" class="btn-outline-light text-white">
            {{ dish.name }}
          </a>
        </td>
        <td style="white-space: normal !important; max-width: 200px;">
            {{ dish.description }}
        </td>
        <td>
          {{ dish.price }}
        </td>
        <td>
          {{ dish.dish_type.name }}
        </td>
      </tr>
    {% endfor %}

    </table>
  {% else %}
    <h3 class="text-white pt-3 mt-5">There is no any dishes</h3>
  {% endif %}

  <a href="{% url "kitchen_app:dish-create" %}" class="btn btn-primary link-to-page">
      Create new dish
    </a>
  </div>

{% endblock content %}

templates/kitchen_app/dishtype_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="text-white pt-3 mt-n5">Are you sure to delete {{ dishtype.name }}?</h1>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <form action="" method="post">
            {% csrf_token %}

            <input type="submit" value="Delete" class="btn btn-primary btn-success">
            <a href="{% url "kitchen_app:dishtype-list" %}" class="btn btn-primary btn-danger">Cancel</a>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/dishtype_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="text-white pt-3 mt-n5">{{ object|yesno:"Update,Create" }} dish type</h1>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit" class="btn btn-primary mt-5">
            <a href="{% url "kitchen_app:dishtype-list" %}" class="btn btn-secondary mt-5">Back</a>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/dishtype_list.html
{% extends "base.html" %}

{% block content %}

  <h1 class="text-white pt-3 mt-n5">Types of Dishes</h1>

  {% if dishtype_list %}
    <table class="table text-white border my-5 align-middle">
      <tr class="fs-4">
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

    {% for dish_type in dishtype_list %}
      <tr class="fs-6">
        <td>
          {{ dish_type.id }}
        </td>
        <td>
          {{ dish_type.name }}
        </td>
        <td>
          <a href="{% url "kitchen_app:dishtype-update" pk=dish_type.id %}" class="btn-outline-light text-white">
            Update
          </a>
        </td>
        <td>
          <a href="{% url "kitchen_app:dishtype-delete" pk=dish_type.id %}" class="btn-outline-light text-white">
            Delete
          </a>
        </td>
      </tr>
    {% endfor %}

    </table>
  {% else %}
    <h2 class="text-white pt-3 mt-n5">There is no any dish types</h2>
  {% endif %}

  <a href="{% url "kitchen_app:dishtype-create" %}" class="btn btn-primary link-to-page">
      Create new type
    </a>

{% endblock content %}

templates/kitchen_app/ingredient_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="text-white pt-3 mt-n5">{{ object|yesno:"Update,Create" }} ingredient</h1>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8">
        <div class="card p-4 shadow-lg">
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit" class="btn btn-primary mt-5">
            <a href="{% url "kitchen_app:ingredient-list" %}" class="btn btn-secondary mt-5">Back</a>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/kitchen_app/ingredient_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1 class="text-white pt-3 mt-5">Ingredients</h1>

  <form action="" method="get">
    {{ search_form|crispy }}
    <input type="submit" value="Search" class="btn btn-primary mt-2">
  </form>

  {% if ingredient_list %}
    <table class="table text-white border my-3 align-middle">
      <tr class="fs-4">
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

    {% for ingredient in ingredient_list %}
      <tr class="fs-6">
        <td>
          {{ ingredient.id }}
        </td>
        <td>
          {{ ingredient.name }}
        </td>
        <td>
          <a href="{% url "kitchen_app:ingredient-update" pk=ingredient.id %}" class="btn-outline-light text-white">
            Update
          </a>
        </td>
        <td>
          <a href="{% url "kitchen_app:ingredient-delete" pk=ingredient.id %}" class="btn-outline-light text-white">
            Delete
          </a>
        </td>
      </tr>
    {% endfor %}

    </table>
  {% else %}
    <h2 class="text-white pt-3 mt-n5">There is no any dish types</h2>
  {% endif %}

  <a href="{% url "kitchen_app:ingredient-create" %}" class="btn btn-primary link-to-page">
      Add new ingredient
    </a>

{% endblock content %}